# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmmenu.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_frmmenu(object):
    def setupUi(self, frmmenu):
        frmmenu.setObjectName("frmmenu")
        frmmenu.setEnabled(True)
        frmmenu.resize(332, 281)
        self.groupBox = QtWidgets.QGroupBox(frmmenu)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 311, 261))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.btnabrircaixas = QtWidgets.QPushButton(self.groupBox)
        self.btnabrircaixas.setGeometry(QtCore.QRect(60, 150, 181, 71))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnabrircaixas.setFont(font)
        self.btnabrircaixas.setObjectName("btnabrircaixas")
        self.btnabrirmovimento = QtWidgets.QPushButton(self.groupBox)
        self.btnabrirmovimento.setGeometry(QtCore.QRect(60, 40, 181, 71))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnabrirmovimento.setFont(font)
        self.btnabrirmovimento.setObjectName("btnabrirmovimento")

        self.retranslateUi(frmmenu)
        QtCore.QMetaObject.connectSlotsByName(frmmenu)
        frmmenu.setTabOrder(self.btnabrirmovimento, self.btnabrircaixas)

    def retranslateUi(self, frmmenu):
        _translate = QtCore.QCoreApplication.translate
        frmmenu.setWindowTitle(_translate("frmmenu", "Menu Principal"))
        self.btnabrircaixas.setText(_translate("frmmenu", "Cadastro de Caixas"))
        self.btnabrirmovimento.setText(_translate("frmmenu", "Cadastro de Movimentos"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    frmmenu = QtWidgets.QWidget()
    ui = Ui_frmmenu()
    ui.setupUi(frmmenu)
    frmmenu.show()
    sys.exit(app.exec_())
