# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmlista.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_frmlista(object):
    def setupUi(self, frmlista):
        frmlista.setObjectName("frmlista")
        frmlista.resize(980, 599)
        self.groupBox = QtWidgets.QGroupBox(frmlista)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 961, 581))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.tabla = QtWidgets.QTableWidget(self.groupBox)
        self.tabla.setGeometry(QtCore.QRect(10, 40, 941, 471))
        self.tabla.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tabla.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tabla.setObjectName("tabla")
        self.tabla.setColumnCount(0)
        self.tabla.setRowCount(0)
        self.tabla.verticalHeader().setVisible(False)
        self.tabla.verticalHeader().setHighlightSections(True)
        self.datemin = QtWidgets.QDateEdit(self.groupBox)
        self.datemin.setGeometry(QtCore.QRect(290, 10, 110, 22))
        self.datemin.setCalendarPopup(True)
        self.datemin.setObjectName("datemin")
        self.datemax = QtWidgets.QDateEdit(self.groupBox)
        self.datemax.setGeometry(QtCore.QRect(440, 10, 110, 22))
        self.datemax.setCalendarPopup(True)
        self.datemax.setDate(QtCore.QDate(2020, 1, 1))
        self.datemax.setObjectName("datemax")
        self.checkdata = QtWidgets.QCheckBox(self.groupBox)
        self.checkdata.setGeometry(QtCore.QRect(240, 10, 51, 21))
        self.checkdata.setObjectName("checkdata")
        self.btnimprimir = QtWidgets.QPushButton(self.groupBox)
        self.btnimprimir.setGeometry(QtCore.QRect(10, 10, 75, 23))
        self.btnimprimir.setObjectName("btnimprimir")
        self.lblsinreg = QtWidgets.QLabel(self.groupBox)
        self.lblsinreg.setGeometry(QtCore.QRect(410, 260, 71, 16))
        self.lblsinreg.setObjectName("lblsinreg")
        self.lblconta = QtWidgets.QLabel(self.groupBox)
        self.lblconta.setGeometry(QtCore.QRect(570, 10, 46, 13))
        self.lblconta.setObjectName("lblconta")
        self.txtbuscar = QtWidgets.QLineEdit(self.groupBox)
        self.txtbuscar.setGeometry(QtCore.QRect(110, 10, 113, 20))
        self.txtbuscar.setObjectName("txtbuscar")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(720, 520, 231, 51))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.lblconta_2 = QtWidgets.QLabel(self.groupBox_2)
        self.lblconta_2.setGeometry(QtCore.QRect(10, 10, 46, 31))
        self.lblconta_2.setObjectName("lblconta_2")
        self.lbltotal = QtWidgets.QLabel(self.groupBox_2)
        self.lbltotal.setGeometry(QtCore.QRect(80, 10, 141, 31))
        self.lbltotal.setObjectName("lbltotal")
        self.lblindice = QtWidgets.QLabel(frmlista)
        self.lblindice.setGeometry(QtCore.QRect(640, 20, 46, 13))
        self.lblindice.setObjectName("lblindice")

        self.retranslateUi(frmlista)
        self.tabla.cellClicked['int','int'].connect(self.lblindice.setNum)
        QtCore.QMetaObject.connectSlotsByName(frmlista)
        frmlista.setTabOrder(self.btnimprimir, self.txtbuscar)
        frmlista.setTabOrder(self.txtbuscar, self.checkdata)
        frmlista.setTabOrder(self.checkdata, self.datemin)
        frmlista.setTabOrder(self.datemin, self.datemax)
        frmlista.setTabOrder(self.datemax, self.tabla)

    def retranslateUi(self, frmlista):
        _translate = QtCore.QCoreApplication.translate
        frmlista.setWindowTitle(_translate("frmlista", "Lista de Movimentos"))
        self.checkdata.setText(_translate("frmlista", "Data"))
        self.btnimprimir.setText(_translate("frmlista", "Imprimir"))
        self.lblsinreg.setText(_translate("frmlista", "Sin Registros"))
        self.lblconta.setText(_translate("frmlista", "TextLabel"))
        self.lblconta_2.setText(_translate("frmlista", "TOTAL:"))
        self.lbltotal.setText(_translate("frmlista", "TOTAL:"))
        self.lblindice.setText(_translate("frmlista", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    frmlista = QtWidgets.QWidget()
    ui = Ui_frmlista()
    ui.setupUi(frmlista)
    frmlista.show()
    sys.exit(app.exec_())
